### PR TITLE
Update tool installation instructions in README

### PR DESCRIPTION
**Pull request by AndrasKovacs**

### CODE REVIEW

**Comment by andreasabel** [comment]
@AndrasKovacs : I added some more instructions how to modify the `PATH`, please have a look.

**Comment by JonasHoefer** [comment]
I had some students who (under windows) installed `alex`, `happy`, and `BNFC` using cabal. They had to manually add the corresponding directory to the path. I am not sure if the analogous directory for stack is added to the path automatically.

**Comment by andreasabel** [comment]
Usually for stack it is `.local/bin`.  This might be in the PATH for some users already since it is the canonical XDG location for user-installed binaries.  I have no clue whether the GHCup installer adds it.

**Comment by AndrasKovacs** [comment]
@andreasabel that's a good addition.

**Review by andreasabel — APPROVED** [review]

**Pull request merged**
